name: Labeler

on:
  schedule:
    - cron: "15 * * * *"

jobs:
  generate_content_label:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}   

    steps:
    - name: User Nutrition Label
      uses: lbonanomi/nutrition-label@1.2
      with:
        count-forked: 'false'
