name: Labeler

on:
  

on:
  schedule:
    - cron: "0 12 * * *"

  workflow_dispatch:

jobs:
  generate_content_label:
    runs-on: ubuntu-latest

    env:
      TOKEN: ${{ secrets.TOKEN }}   

    steps:
    - name: User Nutrition Label
      uses: lbonanomi/nutrition-label@1.4
      with:
        count-forked: 'false'
